//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sibnia.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;

    //using System.Collections.Generic;
    //using Newtonsoft.Json;
    //using Newtonsoft.Json.Linq;

    public partial class Graduirovki
    {
        public int id_graduirovka { get; set; }
        public Nullable<int> id_vesy { get; set; }
        public string nazvanie_graduirovki { get; set; }
        public Nullable<System.DateTime> data_graduirovki { get; set; }
        public string dannye { get; set; }
    
        public virtual Vesy Vesy { get; set; }
    }

    public class GraduationData
    {
        [JsonProperty("X")]
        public Dictionary<string, double> X { get; set; }

        [JsonProperty("Y")]
        public Dictionary<string, double> Y { get; set; }

        // Добавляем все остальные свойства
        [JsonProperty("Z")]
        public Dictionary<string, double> Z { get; set; }

        [JsonProperty("MX")]
        public Dictionary<string, double> MX { get; set; }

        [JsonProperty("MY")]
        public Dictionary<string, double> MY { get; set; }

        [JsonProperty("MZ")]
        public Dictionary<string, double> MZ { get; set; }

        [JsonProperty("X²")]
        public Dictionary<string, double> XSquared { get; set; }

        [JsonProperty("Y²")]
        public Dictionary<string, double> YSquared { get; set; }

        [JsonProperty("Z²")]
        public Dictionary<string, double> ZSquared { get; set; }

        [JsonProperty("X*Y")]
        public Dictionary<string, double> XTimesY { get; set; }

        // Добавьте остальные комбинации по аналогии
    }

    public class GraduationRow
    {
        public string Parameter { get; set; }
        public double X { get; set; }
        public double Y { get; set; }
        public double Z { get; set; }
        public double MX { get; set; }
        public double MY { get; set; }
        public double MZ { get; set; }
    }
} 