//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sibnia.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class sibnia_practicaEntities : DbContext
    {
        public sibnia_practicaEntities()
            : base("name=sibnia_practicaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AerodinamicheskieTruby> AerodinamicheskieTruby { get; set; }
        public virtual DbSet<Graduirovki> Graduirovki { get; set; }
        public virtual DbSet<ModeliSamolyotov> ModeliSamolyotov { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tip_vesov> tip_vesov { get; set; }
        public virtual DbSet<Vesy> Vesy { get; set; }
        public virtual DbSet<Vinty> Vinty { get; set; }
    }
}
