//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sibnia.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModeliSamolyotov
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ModeliSamolyotov()
        {
            this.Vesy = new HashSet<Vesy>();
        }
    
        public int id_model { get; set; }
        public string nazvanie_modeli { get; set; }
        public string nomer_modeli { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vesy> Vesy { get; set; }
    }
}
