    //------------------------------------------------------------------------------
    // <auto-generated>
    //     Этот код создан по шаблону.
    //
    //     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
    //     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
    // </auto-generated>
    //------------------------------------------------------------------------------

    namespace Sibnia.Models
    {
        using System;
        using System.Collections.Generic;
    
        public partial class Vesy
        {
            [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
            public Vesy()
            {
                this.Graduirovki = new HashSet<Graduirovki>();
                this.ModeliSamolyotov = new HashSet<ModeliSamolyotov>();
                this.Vinty = new HashSet<Vinty>();
            }
    
            public int id_vesy { get; set; }
            public string nazvanie_vesov { get; set; }
            public Nullable<int> id_truba { get; set; }
            public Nullable<int> kolichestvo_komponent { get; set; }
            public string komponenty { get; set; }
            public string put_pasporta { get; set; }
            public string put_chertezha { get; set; }
            public Nullable<int> id_tip_vesov { get; set; }
    
            public virtual AerodinamicheskieTruby AerodinamicheskieTruby { get; set; }
            [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
            public virtual ICollection<Graduirovki> Graduirovki { get; set; }
            public virtual tip_vesov tip_vesov { get; set; }
            [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
            public virtual ICollection<ModeliSamolyotov> ModeliSamolyotov { get; set; }
            [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
            public virtual ICollection<Vinty> Vinty { get; set; }
        }
    }
